### ISSUE TITLE
Escaping other special characters like ```

### ISSUE THREAD

**Issue by iamjonny** [mattcone/markdown-guide#152]
I'm trying to wrap markdown in code

![image](https://user-images.githubusercontent.com/28756257/222254333-c6532de5-e600-426f-8db2-b9dd8d88a1e5.png)

```
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
```
```

```

tried to escape the sequence

```
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
\```
```

is it possible to wrap the code element "in a code element"?

**Comment by NightFury711** [comment]
You could wrap the whole code element in three tildes
(~~~) to include the bacticks in the output. Like this:
~~~~
~~~
```[tasklist]
### Tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft issue title
 ```
~~~
~~~~

[Refer this](https://github.com/mattcone/markdown-guide/blob/master/_extended-syntax/fenced-code-blocks.md)
